#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
CONF="/home/dokku/dokku-path-routing/nginx.conf"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #this directory

if [ -f "/etc/nginx/sites-enabled/default" ]; then
    echo "----------> Deleting /etc/nginx/sites-enabled/default"
    sudo rm "/etc/nginx/sites-enabled/default"
fi

[ ! -d "/home/dokku/dokku-path-routing" ] && mkdir "/home/dokku/dokku-path-routing"

echo "----------> Installing $CONF"
[ -f "$CONF" ] || cp $DIR/nginx.conf $CONF
chown -R dokku.dokku "/home/dokku/dokku-path-routing"

sudo /etc/init.d/nginx reload > /dev/null
